name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker Image
      run: |
        docker build -t cloud-attendance-app .

    - name: Test Docker Image (Optional)
      run: |
        docker run --rm cloud-attendance-app python -c "print('Docker test OK')"

    - name: Deploy to Azure VM
      uses: appleboy/ssh-action@v0.1.6
      with:
        host: ${{ secrets.AZURE_VM_IP }}
        username: ${{ secrets.AZURE_VM_USER }}
        key: ${{ secrets.AZURE_VM_SSH_KEY }}
        script: |
          docker stop attendance_container || true
          docker rm attendance_container || true
          docker pull cloud-attendance-app || true
          docker run -d -p 5000:5000 --name attendance_container cloud-attendance-app
